FROM jenkins/xvt-jenkins:latest

COPY --chown=jenkins:jenkins jenkins.jks /var/lib/jenkins/jenkins.jks

ENV JENKINS_OPTS --httpPort=-1 --httpsPort=4343 --httpsKeyStore=/var/lib/jenkins/jenkins.jks --httpsKeyStorePassword=1q2w3e -Dio.jenkins.plugins.artifact_manager_jclouds.s3.S3BlobStoreConfig.deleteArtifacts=true

ENV JAVA_OPTS -Dorg.apache.commons.jelly.tags.fmt.timeZone=Australia/Brisbane

EXPOSE 4343
